### PR TITLE
Adapted PySCeS Thin Layer to BaseThinLayer

### PR DESCRIPTION
**Pull request by JR-1991**
The PySCeS Thin Layer has been adapted to the BaseThinLayer class and utilizes the ```__init__```-method given in the class.

- Incorporates the abstract methods ```optimize``` and ```write``` to perform parameter estimation and writing the gathered parameters to a new ```EnzymeMLDocument``` instance.
- Initial values are applied using the ```enzmldoc.applyModelInitialization```-method which takes the values from a YAML file.
- When writing back, the initial values are kept as such and will only be written to the ```value```-attribute

Example usage:

```python
tl = ThinLayerPysces("Path/To/OMEX", "init_file="Path/To/inifile.yaml")
tl.optimize(model_dir="ModelDir")

enzmldoc = tl.write()
enzmldoc.toFile()
```

---
This change is [Reviewable](https://reviewable.io/reviews/enzymeml/pyenzyme/20)

### CODE REVIEW

**Comment by fbergmann** [comment]
ideally the same things would apply to the COPASI thin layer as well, could we find a way to have the same methods be present on the base class, so that things just work for every modelling tool?

**Comment by JR-1991** [comment]
> ideally the same things would apply to the COPASI thin layer as well, could we find a way to have the same methods be present on the base class, so that things just work for every modelling tool?

I agree, that would be great to have a similar structure in the COPASI thin layer. Are you thinking about to adapt the optimization preparation or complete process in terms of methods? Should we implement this into the base class as well?

**Comment by JR-1991** [comment]
We should also think about to allow an EnzymeMLDocument object as an alternative input. Currently some tests are failing due to files not found and providing a document object as fixture would help.

**Comment by fbergmann** [comment]
currently the method you introduced here into the base class `write`, is in the COPASI TL as `def update_enzymeml_doc(self):`  there i also did not return the enzymeml document in optimize and the update method, as it is available from the class at any point. 

And yes, having a constructor that takes an enzyme ml document, instead to always have to read from archive would be a good idea.

**Pull request merged**
