### PR TITLE
add function to TL_Pysces to write EnzymeML document with fit results

### LINKED ISSUE #15: Add function in TL_Pysces to write results from PySCeS back to EnzymeML
The thinlayer for PySCeS fits the model and returns the results as a lmfit result but there is no automatic option to write the results back to the EnzymeML document.

### PR DESCRIPTION
**Pull request by HannahDi**
# Changes
Add function to automatically add fit results to the EnzymeML document and write it.
Example code:
```
psc = ThinLayerPysces('PGM-ENO.omex')  
fit = psc.runOptimisation()  
psc.writeEnzymeML('PGM-ENO_results')
```
This will change the name of the EnzymeML document to PGM-ENO_results and create the new document.
If no name is given, the old EnzymeML document will be overwritten.
# Motivation
closes #15

---
This change is [Reviewable](https://reviewable.io/reviews/enzymeml/pyenzyme/16)

### CODE REVIEW

**Review by JR-1991 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/enzymeml/pyenzyme/16)* status: all files reviewed, 3 unresolved discussions (waiting on @HannahDi and @jmrohwer)

___
*[pyenzyme/thinlayers/TL_Pysces.py, line 116 at r1](https://reviewable.io/reviews/enzymeml/pyenzyme/16#-MnkTDRo7dDL-VPIX5d0:-MnkTDRo7dDL-VPIX5d1:bhz4g6d) ([raw file](https://github.com/enzymeml/pyenzyme/blob/292b7926bc99fbea438dc8f8decc747b65cfa9da/pyenzyme/thinlayers/TL_Pysces.py#L116)):*
> ```Python
>         return self.fit
> 
>     def _addResultsToEnzymeML(self):
> ```

Maybe move the helper function under the one that utilizes it. It is easier to understand the whole concept if you scroll down. 
___
*[pyenzyme/thinlayers/TL_Pysces.py, line 127 at r1](https://reviewable.io/reviews/enzymeml/pyenzyme/16#-MnkOHpKDkZtIfl7cMcB:-MnkOHpL0TOvU27vQL-O:b-5y9t44) ([raw file](https://github.com/enzymeml/pyenzyme/blob/292b7926bc99fbea438dc8f8decc747b65cfa9da/pyenzyme/thinlayers/TL_Pysces.py#L127)):*
> ```Python
>             parameters[parameter_name] = (value, unit)
> 
>     def writeEnzymeML(self, name=None):
> ```

Maybe add the possibiity to customize path and filename, but provide your currrent setup as default, maybe?
___
*[pyenzyme/thinlayers/TL_Pysces.py, line 135 at r1](https://reviewable.io/reviews/enzymeml/pyenzyme/16#-MnkSxql8J4l-BBLiHWK:-MnkSxql8J4l-BBLiHWL:b6mkegs) ([raw file](https://github.com/enzymeml/pyenzyme/blob/292b7926bc99fbea438dc8f8decc747b65cfa9da/pyenzyme/thinlayers/TL_Pysces.py#L135)):*
> ```Python
>             name (str): new name for EnzymeML document
>         '''
>         if name is not None:
> ```

You can simplify this line to 

```if name:```

This expression evaluates to the same as yours.

**Comment by jmrohwer** [comment]
> 
> > ```python
> >         return self.fit
> > 
> >     def _addResultsToEnzymeML(self):
> > ```
> 
> Maybe move the helper function under the one that utilizes it. It is easier to understand the whole concept if you scroll down.

I agree.

> > ```python
> >             parameters[parameter_name] = (value, unit)
> > 
> >     def writeEnzymeML(self, name=None):
> > ```
> 
> Maybe add the possibiity to customize path and filename, but provide your currrent setup as default, maybe?

I see this is already implemented.

**Review by jmrohwer — CHANGES_REQUESTED** [review]
I am happy with the changes and comments proposed by Jan. However, we have to decide how to deal with the error estimates for the parameters. In the current version these are not entered into the EnzymeML doc. But error estimates are an integral part of enzyme kinetic parameter estimation and we also have to deal with that in terms of STRENDA DB entry. 

So, in general SBML core does not support errors for parameters, but we could look at the SBML level 3 `distrib` package, which deals with statistical distributions. We have to decide how to deal with errors in general, i.e. using `distrib`, or with custom EnzymeML annotations. I would prefer the first option, as we don't want to reinvent the wheel. Maybe we can discuss this on Monday.

**Comment by jmrohwer** [comment]
Another point we should consider is the type of error estimate and if/how this should be specified. In the use case here, lmfit estimates the errors from the covariance matrix during the optimization. However, there are also other approaches, such as estimating confidence intervals (at a given probability, typically 95%) from the profile likelihood. `lmfit` has some built in support for this, but in my own work I am looking at extending this. The profile likelihood gives a better indication of parameter identifiability than the simple estimate from the covariance matrix. We can maybe discuss this on Monday as well.

**Review by JR-1991 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/enzymeml/pyenzyme/16)* status: all files reviewed, 4 unresolved discussions (waiting on @HannahDi)

___
*[pyenzyme/thinlayers/TL_Pysces.py, line 116 at r2](https://reviewable.io/reviews/enzymeml/pyenzyme/16#-MoYH4OG3J4mIfGMDZ3p:-MoYH4OG3J4mIfGMDZ3q:b-ik3i8i) ([raw file](https://github.com/enzymeml/pyenzyme/blob/7db621e50c9a0a9c3bbf9203e177264288be4374/pyenzyme/thinlayers/TL_Pysces.py#L116)):*
> ```Python
>         return self.fit
> 
>     def writeEnzymeML(self, name=None, path=None):
> ```

You can default the argument to "." and remove the if/else at the bottom.

**Pull request closed without merging**
