### PR TITLE
PySCeS ThinLayer: Fit multiple replicates, plot fit result

### PR DESCRIPTION
**Pull request by jmrohwer**
This pull request implements 4 features/bug fixes:
- The PySCeS TL can now fit datasets with multiple replicates
- A function has been added to plot the experimental data together with the fitted model
- Various cases where parameters with a zero value were not loaded/saved, have been fixed (`if self.value:` -> `if self.value is not None`).
- The PySCeS loading of the model has been optimized, the conversion to PSC is only done if the EnzymeMLDoc is newer (this process takes time), and a bug with compartment volumes not equal to 1 has been fixed.

The new functionality is demonstrated with an example notebook that I am sharing with @JR-1991 via Google Colab. Any other reviewers, let me know and I'll be happy to share it. It takes the Model 3 from Scenario 4 from the Lauterbach 2022 paper and fits this with PySCeS. The fitted parameters are the same (within small errors) as obtained with direct fitting in the Jupyter notebook using `lmfit` and `odeint`.

---
This change is [Reviewable](https://reviewable.io/reviews/enzymeml/pyenzyme/46)

### CODE REVIEW

**Review by jmrohwer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/enzymeml/pyenzyme/46)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @JR-1991)

___
*[`pyenzyme/thinlayers/TL_Pysces.py` line 288 at r1](https://reviewable.io/reviews/enzymeml/pyenzyme/46#-N4XlYqe4r5PtA3HugxH:-N4XlYqf-8PKXVWMPGmi:b-x4yqub) ([raw file](https://github.com/enzymeml/pyenzyme/blob/6fb0709f2f2daf89f6a870e67e6c9cdefbda6e99/pyenzyme/thinlayers/TL_Pysces.py#L288)):*
> ```Python
>         return pd.DataFrame(np.hstack(output).T, columns=self.model.species)
> 
>     def _get_replicate_info(self, time):
> ```

@jr-1991 I'd be interested to know if there is a better way of doing this. The point is that in the experimental data all the replicates are vertically stacked above each other, yet each replicate requires only a single simulation (we don't have to repeat the simulation), and this is what I'm trying to achieve here.
___
*[`pyenzyme/thinlayers/TL_Pysces.py` line 301 at r1](https://reviewable.io/reviews/enzymeml/pyenzyme/46#-N4XmR-kBz1Hj25BGvJ-:-N4XmR-l9EcVLFF8lcXG:basxkck) ([raw file](https://github.com/enzymeml/pyenzyme/blob/6fb0709f2f2daf89f6a870e67e6c9cdefbda6e99/pyenzyme/thinlayers/TL_Pysces.py#L301)):*
> ```Python
>         return (time[:i].values, num_reps)
> 
>     def plot_fit(self):
> ```

This is quite useful and if there is more than one reagent for which there is data, they are plotted with different colours. It is of course not as elegant as `EnzymeMLDocument.visualize()`but that one can use `seaborn.FacetGrid` because it is only a single dataframe. Here we are plotting data from two different dataframes, and moreover we want to plot the modelling data with more time-points than the experimental data to give smooth curves. So I think the only way to do this is directly with matplotlib, which gives less flexibility for interactive visualization. I have set this to plot 3 columns and the number of rows to be adjusted automatically depending number of measurements. However, I am open for suggestions for improving this. I think a method to quickly visualize a fit with data and model is very important in the library.

**Review by JR-1991 — APPROVED** [review]

**Review by JR-1991 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/enzymeml/pyenzyme/46)* status: all files reviewed, 2 unresolved discussions (waiting on @jmrohwer)

___
*[`pyenzyme/thinlayers/TL_Pysces.py` line 288 at r1](https://reviewable.io/reviews/enzymeml/pyenzyme/46#-N4XlYqe4r5PtA3HugxH:-N5ES7cX9ZWwefeY2chv:bl6wbcs) ([raw file](https://github.com/enzymeml/pyenzyme/blob/6fb0709f2f2daf89f6a870e67e6c9cdefbda6e99/pyenzyme/thinlayers/TL_Pysces.py#L288)):*
<details><summary><i>Previously, jmrohwer (Johann Rohwer) wrote…</i></summary><blockquote>

@jr-1991 I'd be interested to know if there is a better way of doing this. The point is that in the experimental data all the replicates are vertically stacked above each other, yet each replicate requires only a single simulation (we don't have to repeat the simulation), and this is what I'm trying to achieve here.
</blockquote></details>

Thats a great solution! I was wondering if it might be an option to modify the exportData function to not stack replicates vertically, but to provide a Dataframe for each species. This way everything is stacked horizontally. I have a feeling that this might also be more handy for other use cases. This would then be another optional argument to the function to change behaviour. What do you think?

**Review by JR-1991 — APPROVED** [review]
As we previously discussed, the extension is great. Will merge the changes into main.

> *[Reviewable](https://reviewable.io/reviews/enzymeml/pyenzyme/46#-:-NEyrK0i0Tf2wk9uBNhT:bqmjqe6)* status: all files reviewed, 2 unresolved discussions (waiting on @jmrohwer)

**Review by JR-1991 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/enzymeml/pyenzyme/46)* status: all files reviewed, 2 unresolved discussions (waiting on @jmrohwer)

**Pull request merged**
